const MESSAGE_KEY_INSERT_TO_DB = 'InsertToDB';
const QIITA_ARTICLE_TITLE_TAG = 'h1';
const QIITA_ARTICLE_TAG_HREF = '/tags';
const QIITA_POSTED_DATE_TAG = 'time';
const QIITA_API_ENDPOINT = 'https://qiita.com/api/v2';

export { 
  MESSAGE_KEY_INSERT_TO_DB,
  QIITA_ARTICLE_TITLE_TAG,
  QIITA_ARTICLE_TAG_HREF,
  QIITA_POSTED_DATE_TAG, 
  QIITA_API_ENDPOINT
}